package nl.kii.async;

import nl.kii.async.AsyncMap;
import nl.kii.promise.Promise;

/**
 * An AsyncMap that has Strings as keys and allows for adding of values
 * using autogenerated keys.
 */
@SuppressWarnings("all")
public interface IndexedAsyncMap<V extends Object> extends AsyncMap<String, V> {
  /**
   * Add a value on the default index. Promises the new key of the value.
   */
  public abstract Promise<String> add(final V index);
  
  /**
   * Add a value on the specified index. Promises the new key of the value.
   */
  public abstract Promise<String> add(final V value, final String index);
  
  /**
   * Generate a new key for the given index.
   */
  public abstract Promise<String> newKey(final String index);
}
